//addSbtPlugin("com.codecommit" % "sbt-github-packages" % "0.5.3")
// addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.6.1")
addSbtPlugin("com.github.sbt" % "sbt-pgp" % "2.2.1")
scalaCopy codeaddSbtPlugin("com.jsuereth" % "sbt-pgp" % "2.1.2")
addSbtPlugin("com.typesafe.sbt" % "sbt-sonatype" % "3.9.10")