name: Publish Jar on Push to main

on:
  workflow_dispatch:
  push:
    branches: ['master']

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0

      - uses: actions/setup-java@v3.10.0
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: sbt

      - name: Publish Package - hl7-pet
        run: sbt publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
