name: Build & Publish

on:
  workflow_dispatch:
  push:
    branches: ['master']

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK And SBT
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "sbt"

      - name: Decrypt and Import GPG Key
        run: |
            gpgconf --kill gpg-agent || true
            gpgconf --launch gpg-agent || true
            echo "$PGP_PRIVATE_KEY" | gpg --batch --no-tty --import
        env:
          PGP_PRIVATE_KEY: '${{ secrets.GPG_PRIVATE_KEY_BORIS }}'
          PGP_PASSPHRASE: '${{ secrets.GPG_PASSPHRASE_BORIS }}'

      - name: Publish to Maven Repository
        env:
          PGP_PRIVATE_KEY: '${{ secrets.GPG_PRIVATE_KEY }}'
          PGP_PASSPHRASE: '${{ secrets.GPG_PASSPHRASE_BORIS }}'
          SONATYPE_USERNAME: '${{ secrets.SONATYPE_USERNAME }}'
          SONATYPE_PASSWORD: '${{ secrets.SONATYPE_PASSWORD }}'
        run: sbt ci-release
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Publish to GitHub Packages
      #   run: sbt publish
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
