name: Build & Publish

on:
  #workflow_dispatch:
  push:
    branches: 
    - feature/artifact-publish

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Setup JDK And SBT
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "sbt"

      - name: Decrypt and Import GPG Key
        run: |
            gpgconf --kill gpg-agent || true
            gpgconf --launch gpg-agent || true
            echo "$GPG_SECRET" | base64 --decode | gpg --import
        env:
          GPG_SECRET: ${{ secrets.GPG_PRIVATE_KEY_BORIS }}

      - name: Publish to Maven Repository
        run: | 
            sbt publishSigned
            sbt sonatypeBundleRelease
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE_BORIS }}
          GPG_SECRET: ${{ secrets.GPG_PRIVATE_KEY_BORIS }}

      # - name: Publish to GitHub Packages
      #   run: sbt publish
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
