name: Build & Publish

on:
  workflow_dispatch:
  push:
    branches: ['master']

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Setup JDK And SBT
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "sbt"

      - name: Decrypt and Import GPG Key
        run: |
            gpgconf --kill gpg-agent || true
            gpgconf --launch gpg-agent || true
            echo "${{ secrets.GPG_PRIVATE_KEY_BORIS }}" | gpg --batch --no-tty --import
        env:
          PGP_SECRET: ${{ secrets.GPG_PRIVATE_KEY_BORIS }}

      - name: Publish to Maven Repository
        run: sbt clean compile publish
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          PGP_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE_BORIS }}
          PGP_SECRET: ${{ secrets.GPG_PRIVATE_KEY_BORIS }}

      # - name: Publish to GitHub Packages
      #   run: sbt publish
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
