name: Release

on:
  push:
    tags:
       - 'v*.*.*'  # Adjust the tag pattern to match your versioning scheme
  release:
     types: [created]  # Trigger the workflow when a release is created
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: sbt
        
    - name: Install gnupg
      run: sudo apt update && sudo apt install -y gnupg

    - name: Import PGP secret
      run: echo "${{ secrets.PGP_SECRET }}" | base64 --decode | gpg --batch --import

    - name: Publish to Maven Repository
      run: sbt clean publishSigned sonatypeBundleRelease
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}