name: Release

on:
  push:
    branches: 
          - maven-central
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: sbt

    - name: Install gnupg
      run: sudo apt update && sudo apt install -y gnupg

    - name: Import PGP secret
      run: echo "${{ secrets.PGP_SECRET }}" | gpg --batch --no-tty --import

    - name: Refresh version tag
      run: git pull --tags

    - name: Publish to Maven Repository
      run: sbt clean publishSigned sonatypeBundleRelease
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}